// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/15/2025, 11:16:03 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/thibautdavoult/code/perso/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thibautdavoult/code/perso/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thibautdavoult/code/perso/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thibautdavoult/code/perso/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/thibautdavoult/code/perso/portfolio/plugins/**/*.{js,ts,mjs}","/Users/thibautdavoult/code/perso/portfolio/composables/**/*.{js,ts,mjs}","/Users/thibautdavoult/code/perso/portfolio/utils/**/*.{js,ts,mjs}","/Users/thibautdavoult/code/perso/portfolio/pages/about.vue","/Users/thibautdavoult/code/perso/portfolio/pages/index.vue","/Users/thibautdavoult/code/perso/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/thibautdavoult/code/perso/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/thibautdavoult/code/perso/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;