name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NITRO_PRESET: github-pages
  NODE_ENV: production

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          npm ci
          npm list @nuxt/content || true

      - name: Generate static files
        run: |
          npm run generate
          ls -la .output/public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 